= Quarkus Asyncapi Scanner

include::./includes/attributes.adoc[]

This extension creates an AsyncApi-document, describing data your server publishes/subscribes to/from Kafka-topics.

It does this by

* scanning for annotations `@Channel, @Outgoing and @Incoming` in your project,
* reading topics and descriptions from microprofile-configuration and
* reading data from running kafka

The result can be viewed as html or svg or downloaded as yaml, json or plant-uml (localhost://[quarkus.http.root-path]/asyncapi.[html|svg|yaml|json|puml]).

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.asyncapi:quarkus-asyncapi` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.asyncapi</groupId>
    <artifactId>quarkus-asyncapi-scanner</artifactId>
    <version>{project-version}</version>
</dependency>
----

[[extension-configuration-reference]]
== Extension Configuration Reference

[TIP]
For more information about the extension configuration please refer to the <<configuration-reference, Configuration Reference>>.

include::includes/quarkus-asyncapi-annotation-scanner.adoc[leveloffset=+1, opts=optional]

== Migration to V1 (switch from AsyncApi v2.6.0 to v3.0.0)
The structure of asyncApi has multiple breaking changes. See https://www.asyncapi.com/docs/migration/migrating-to-v3[migration to V3] for details.
To apply to these changes following changed in the extension-configuration:

* `server.url` is divided into `server.host` and `server.pathname` (see https://www.asyncapi.com/docs/migration/migrating-to-v3#server-url-splitting-up[server-url splitting up])
